---
title: 'nsink: An R package for flow path nitrogen removal estimation'
tags:
- R
- nitrogen
- nitrogen sinks
- landscape
- gis
date: "`r lubridate::today()`"
output: pdf_document
authors:
- name: Jeff Hollister
  orcid: 0000-0002-9254-9740
  affiliation: 1
- name: Dorothy Q. Kellogg
  orcid: 0000-0002-9509-4606
  affiliation: 2
- name: Qian Lei-Parent
  orcid: 0000-0002-1904-2513
  affiliation: 3
bibliography: paper.bib
affiliations:
- name: U. S. Environmental Protection Agency, Atlantic Coastal Environmental Sciences
    Division
  index: 1
- name: University of Rhode Island, Department of Natural Resources Science
  index: 2
- name: University of Connecticut, Center for Land Use Education and Research
  index: 3
---
  
  
# Summary

The `nsink` package estimates cumulative nitrogen (N) removal along a specified flow path and is based on methodologies outlined in Kellogg et al. [ -@kellogg2010geospatial]. For a user-specified watershed, `nsink` downloads all required datasets from public datasets in the United States, prepares data for use, summarizes N removal along a flow path and creates several static watershed maps.  The results of an `nsink` analysis may be exported to standard geospatial files for use in other applications.  

# Statement of need

Excess N delivery via surface water to downstream aquatic resources contributes to impaired water quality and leads to several ecosystem impacts including harmful algal blooms (HABs) and hypoxia [@rabalais2002beyond]. Identifying landscape N sinks (i.e., areas where N is effectively removed from the aquatic system) and analysing N delivery at the watershed scale is helpful to watershed managers, land use planners and conservation organizations.  The theoretical underpinnings for identifying N sinks rely on decades of research and are explained in Kellogg et al. [-@kellogg2010geospatial]. 

The first implementation of this approach was done case-by-case.  Data acquisition and manipulation were mostly manual and took weeks to months to complete for a single watershed.  The effort required for the analysis limited it's application as scaling beyond a few pilot studies was not feasible.  The goal of `nsink` was to address this limitation and provide an open source solution that could be run on a single small watershed in minutes to hours with minimal manual input.

# The `nsink` package

## Package Installation
The `nsink` package is available from <https://github.com/usepa/nsink> and may be installed in R with the following:

```r
# If not installed, install remotes
install.packages("remotes")

# Install nsink from GitHub
remotes::install_github("USEPA/nsink", build_vignettes = TRUE)
```

## Package Details

The `nsink` package is designed around the major steps in running a N-Sink analysis and includes the following:

1. Prepare for analysis
    - Get data
    - Prepare data for analysis
    - Calculate relative N removal layer for hydric soils, lakes and streams.
2. Run an point-based analysis 
    - Calculate a flow path 
    - Summarize relative N removal along a flow path
3. Run a watershed-based analysis
    - Develop static maps
    - Generate output datasets

### Required Data

The ability to run an `nsink` analysis relies on several national scale datasets for the United States.  By limiting our approach to these national datasets we are ensuring scalability of `nsink` because the datasets will be available for most locations in the United States.  The datasets that `nsink` uses are the National Hydrography Dataset Plus (NHDPlus), Soil Survey Geographic Database (SSURGO), the National Land Cover Dataset (NLCD) land cover, and the National Land Cover Dataset (NLCD) impervious surface [ADD CITATION FOR DATASETS]. These datasets are all available via either an Application Programming Interface (API) or via direct download.   

### Dependencies

The `nsink` package depends on several existing R packages to facilitate spatial data handling, data acquisition, data management, data analysis and data processing.  These are detailed in Table 1.  

Table 1. R Package Dependencies for the `nsink` package

|Package|Task|Citation|
|-------|----|--------|
|`sf`|Spatial Data Handling and Analysis|@sfpaper; @sf|
|`raster`|Spatial Data Handling and Analysis|@raster|
|`stars`|Spatial Data Handling and Analysis|@stars|
|`fasterize`|Spatial Data Handling and Analysis|@fasterize|
|`lwgeom`|Spatial Data Handling and Analysis|@lwgeom|
|`gstat`|Spatial Data Handling and Analysis|@gstatpaper2004; @gstatpaper2016; @gstat|
|`sp`|Spatial Data Handling and Analysis|@sppaper; @spbook; @sp|
|`units`|Unit Transformations|@unitspaper; @units|
|`FedData`|Data Acquisition|@feddata|
|`httr`|Data Acquisition|@httr|
|`dplyr`|Data Management and Analysis|@dplyr|
|`zoo`|Data Management and Analysis|@zoopaper; @zoo|
|`igraph`|Data Management and Analysis|@igraphpaper; @igraph|
|`readr`|Data Management and Analysis|@readr|
|`foreign`|Data Management and Analysis|@foreign|
|`rlang`|Data Management and Analysis|@rlang|
|`furrr`|Parallel Processing|@furrr|
|`future`|Parallel Processing|@futurepaper; @future|



### Functionality

Currently, `nsink` provides 10 exported functions to facilitate a flow path analysis of relative N removal. 

- `nsink_get_huc_id()`: A function for searching the name of a USGS Watershed Boundary Dataset Hydrologic Unit (<https://www.usgs.gov/core-science-systems/ngp/national-hydrography/watershed-boundary-dataset>) and retrieving its 12-digit Hydrologic Unit Code (HUC).  
- `nsink_get_data()`: Using any acceptable HUC ID (e.g. 2-digit to 12-digit), this function downloads the NHDPlus, SSURGO, NLCD Land Cover, and the NLCD Impervious for that HUC.   
- `nsink_prep_data()`: `nsink` needs data in a common coordinate reference system, from mutliple NHDPlus tables, and from different portions of SSURGO.  This function completes these data preparation steps and outputs all data, clipped to the HUC boundary.
- `nsink_calc_removal()`: Quantifying relative N removal across a landscape is a key aspects of an `nsink` analysis.  The `nsink_calc_removal()` function takes the object returned from `nsink_prep_data()` and calculates relative N removal for each landscape sink.  See Kellogg et al [-@kellogg2010geospatial] for details on relative N removal estimation for each sink.
- `nsink_generate_flowpath()`: This function uses a combination of flow determined by topography, via a flow-direction raster, for the land-based portions of a flow path and of downstream flow along the NHDPlus stream network.   
- `nsink_summarize_flowpath()`: Summarizing removal along a specified flow path requires relative N removal and a generated flow path.  This function uses these and returns a  summary of relative N removal along a flow path for each sink. 
- `nsink_generate_static_maps()`: This function analyzes N removal at the watershed scale by summarizing the results of multiple flow paths. Four static maps are returned: 1)removal efficiency; 2)loading index; 3)transport index; 4)delivery index.  Removal efficiency is a rasterized version of the `nsink_calc_removal()` output.  Loading index is N sources based on NLCD categories.   Transport index is a heat map with the cumulative relative N removal along flow paths originating from a grid of points, density set by the user, across a watershed, highlighting the gradient of downstream N retention. Delivery index is the result of multiplying the loading index and the transport index, and shows potential N delivery from different sources, taking into account the relative N removal as water moves downstream. 
- `nsink_plot()`: A function that plots each raster in the list returned from `nsink_generate_static_maps()`.   
- `nsink_build()`: One of the drivers behind the development of the `nsink` package was to provide `n-sink` analysis output that could be used more broadly (e.g. within a GIS).  The `nsink_build()` runs a complete `nsink` analysis and outputs R objects, shapefiles and/or TIFFs.
- `nsink_load()`: Essentially the inverse of the `nsink_build()` function, this function takes a folder of files, likely created by `nsink_build()`, and reads them into R.

The R package documentation contains both a detailed description of each function and a vignette that outlines a typical workflow for running an N-Sink analysis with the `nsink` package.  Upon install, the vignette is accessed in R with `vignette("intro", package = "nsink")`. 

# Acknowledgements
    
Many people have contributed in various ways to the development of the N-Sink concept.  In particular, we would like to thank, Chet Arnold, Cary Chadwick, David Dickson, and Emily Wilson of the University of Connecticut's Center for Land Use Education and Research as well as Peter August, Chris Damon, and Art Gold of the University of Rhode Island's Department of Natural Resources Science.  Both the UCONN and URI crews have contributed tremendously to the development of the N-Sink concept.  Additionally, we are grateful to X X, X X, X X, Joe LiVolsi, Tim Gleason, and Wayne Munns from the US EPA, Atlantic Coastal Environmental Sciences Division for constructive reviews of this paper. The views expressed in this article are those of the authors and do not necessarily represent the views or policies of the U.S. Environmental Protection Agency. Any mention of trade names, products, or services does not imply an endorsement by the U.S. Government or the U.S. Environmental Protection Agency. The EPA does not endorse any commercial products, services, or enterprises. This contribution is identified by the tracking number ORD-XXXXX of the Atlantic Coastal Environmental Sciences Division, Office of Research and Development, Center for Environmental Measurement and Modeling, US Environmental Protection Agency.
    
# References
