#' Summarize nitrogen removal along a flowpath
#'
#' Nitrogen removal varies along a flowpath as they include different land cover
#' and waterbody types that have different nitrogen reduction capabilities.
#' This function takes a flowpath generated by
#' \code{\link{nsink_generate_flowpath}} as required input and returns and
#' estimate of total flow path removal as well as removal by type.
#'
#' @param flowpath a flowpath to summarize nitrogen removal
#' @param method a character string which determines if the caclulations are
#'               done using the raster method or a hybrid method
#'               (not currently implemented).
#' @return A list is returned that contains rasterized removal flowpath, a
#' rasterized type flowpath, and summary removal stasitics
#'
#' @export
#' @examples
#' \dontrun{
#'
#'
#'
#'
#' }
nsink_summarize_flowpath_removal <- function(flowpath, method = c("raster")){

}

#' Create rasters of removal and the type of removal
#'
#' This function takes a flowpath as input and extracts out the nitrogen removal
#' and they type of removal.
#'
#' @param flowpath a flowpath to summarize nitrogen removal
#'
nsink_create_removal_rasters <- function(flowpath){


}

nsink_filter_removal_rasters <- function(flowpath_raster){


}

nsink_calc_total_reduction <- function(){


}

nsink_create_segment_ids <- function(){


}

nsink_create_summary <- function(){


}
