#' Summarize nitrogen removal along a flowpath
#'
#' Nitrogen removal varies along a flowpath as they include different land cover
#' and waterbody types that have different nitrogen reduction capabilities.
#' This function takes a flowpath generated by
#' \code{\link{nsink_generate_flowpath}} as required input and returns and
#' estimate of total flow path removal as well as removal by type.
#'
#'
#' @param flowpath a flowpath to summarize nitrogen removal
#' @param removal the removal raster stack or removal list, generated by
#'                \code{\link{nsink_calc_removal}}
#' @param method a character string which determines if the caclulations are
#'               done using the raster method or a hybrid method
#'               (not currently implemented).
#' @param filter_window A numeric value indicating the size of the filter
#'                      window. Default value is 3.  See argument description
#'                      for \code{width} from \code{\link{rollmax}}. Only used
#'                      if the raster method is chosen.
#' @return A list is returned that contains rasterized removal flowpath, a
#' rasterized type flowpath, total removal, and summary removal stasitics
#'
#' @importFrom zoo rollmax
#' @importFrom raster rasterize extract
#' @export
#' @examples
#' \dontrun{
#' library(nsink)
#' library(sf)
#' library(lwgeom)
#' niantic_huc <- nsink_get_huc_id("Niantic River")$huc_12
#' niantic_data <- nsink_get_data(niantic_huc)
#' aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
#' niantic_nsink_data <- nsink_prep_data(niantic_huc, projection = aea)
#' removal_rasters <- nsink_calc_removal(niantic_nsink_data)
#' removal_hybrid <- nsink_calc_removal(niantic_nsink_data, method = "hybrid")
#' pt <- c(1948121,2295822)
#' start_loc <- st_sf(st_sfc(st_point(c(pt)), crs = aea))
#' fp <- nsink_generate_flowpath(start_loc, niantic_nsink_data)
#' fp_hybrid <- nsink_generate_flowpath(start_loc, niantic_nsink_data,
#'                                      method = "hybrid")
#' nsink_summarize_flowpath(fp, removal_rasters)
#' nsink_summarize_flowpath(fp_hybrid, removal_hybrid, method = "hybrid")
#' }
#' TODO Deal with adjacent hydrics, prior to entering stream network with
#'      different removal by combining and averaging?
#' TODO Why are there adjacent lakes with different removal values?
#' TODO Remove hydric that occurs once flowpath enters the stream network.
#'      Replace with values from either side
#'
nsink_summarize_flowpath <- function(flowpath, removal,
                                     method = c("raster", "hybrid"), filter_window = 3){
  method <- match.arg(method)
  if(method == "raster"){
    fp_removal_raster <- rasterize(flowpath, removal[[1]], 1, max) *
      removal[[1]]
    fp_type_raster <- rasterize(flowpath, removal[[2]], 1, max) *
      removal[[2]]
    removal <- extract(removal[[1]], flowpath, along = TRUE)[[1]]
    type <- extract(removal[[2]], flowpath, along = TRUE)[[1]]
    removal <- rollmax(removal, filter_window)
    type <- rollmax(type, filter_window)
    total_removal <- nsink_calc_total_removal(removal) #This looks like what is left, not removal
    removal_summary <- nsink_create_summary(removal, type)
    output <- list(flowpath_removal = fp_removal_raster,
                   flowpath_type = fp_type_raster,
                   total_removal = total_removal,
                   removal_summary = removal_summary)
    return(output)
  } else if(method == "hybrid"){
    browser()
    #TODO extract land removal for flowpath ends
    #TODO get per segment removal from network
    #TODO add it all together

  }
}

#' Calculate total nitrogen removal
#'
#' Nitrogen removal along a flowpath is determined by the types of landcover
#' encountered.  This function takes a vector of removal estimates and
#' calculates the total nitrogen removal for that flowpath.
#'
#' @param flowpath_vector a vector of removal values extracted from a nitrogen
#'                        removal raster generated by
#'                        \code{\link{nsink_extract_flowpath}}.

#' @return A single numeric vector for total nitrogen removal along the flowpath
#'
#' @importFrom zoo rollapply
#' @keywords internal
nsink_calc_total_removal <- function(flowpath_vector){
  fp_last <- zoo::rollapply(flowpath_vector, width = 2, partial = TRUE,
                            function(x) ifelse(x[1]==x[2],0, x[1]))
  fp_last <- ifelse(is.na(fp_last),flowpath_vector[length(flowpath_vector)],fp_last)
  fp_last_removal <- 1-fp_last
  total_removal <- cumprod(c(100,fp_last_removal))
  min(total_removal)
}

#' Create ID's for unique values in a vector
#'
#' This functions takes a vector of values and creates a unique ID for adjacent
#' and identical values.
#'
#' @param x a vector of values to create unique ID's
#'
#' @return a vector of unique ID's
#'
#' @keywords internal
nsink_create_segment_ids <- function(x){
  y<-vector("numeric", length(x))
  y_id<-vector("numeric", length(x))
  for(i in seq_along(x)){
    if(i == 1){
      y[i] <- i
    } else {
      y[i] <- ifelse(x[i]==x[i-1], FALSE,i)
    }
  }
  for(i in seq_along(y)){
    if(i == 1){
      y[1] <- y[1]
    } else {
      y[i] <- ifelse(y[i] == 0, y[i-1], y[i])
    }
  }
  y
}


#' Create a nitrogen removal summary
#'
#' This functions takes a nitrogen removal and removal type flowpath and creates
#' a data frame that summarizes the removal along that flowpath
#'
#' @param removal_vector A flowpath vector of nitrogen removal generated by
#'                       \code{\link{nsink_extract_flowpath}}.
#' @param type_vector A flowpath vector of removal type generated by
#'                    \code{\link{nsink_extract_flowpath}}.
#'
#' @return a data frame summarizing nitrogen removal along a flowpath
#' @import dplyr
#' @keywords internal
nsink_create_summary <- function(removal_vector, type_vector){
  type_removal_df <- data.frame(type_code = type_vector,
                                removal = removal_vector,
                                stringsAsFactors = FALSE)
  type_removal_df <- mutate( type_removal_df,
                             segment_type = case_when(type_code == 0 ~ "No Removal",
                                                      type_code == 1 ~ "Hydric",
                                                      type_code == 2 ~ "Stream",
                                                      type_code == 3 ~ "Lake/Pond"),
                             segment_id = nsink_create_segment_ids(paste(type_code, removal)))
  type_removal_df <- group_by(type_removal_df, segment_id, segment_type)
  type_removal_df <- summarize(type_removal_df, length = n()*30,
                               n_removal = max(removal))
  type_removal_df <- ungroup(type_removal_df)
  n <- nrow(type_removal_df)
  output <- mutate(type_removal_df, n_in =
                       round(cumprod(c(100,1-n_removal))[-n],2),
                     n_out = round(cumprod(c(100,1-n_removal))[-1],2),
                     percent_removal = round(n_removal*100,3))
  output <- select(output, segment_type, length, percent_removal, n_in, n_out)
  output
}





































