#' Summarize nitrogen removal along a flowpath
#'
#' Nitrogen removal varies along a flowpath as they include different land cover
#' and waterbody types that have different nitrogen reduction capabilities.
#' This function takes a flowpath generated by
#' \code{\link{nsink_generate_flowpath}} as required input and returns and
#' estimate of total flow path removal as well as removal by type.
#'
#' @param flowpath a flowpath to summarize nitrogen removal
#' @param method a character string which determines if the caclulations are
#'               done using the raster method or a hybrid method
#'               (not currently implemented).
#' @return A list is returned that contains rasterized removal flowpath, a
#' rasterized type flowpath, and summary removal stasitics
#'
#' @export
#' @examples
#' \dontrun{
#'
#'
#'
#'
#' }
nsink_summarize_flowpath_removal <- function(flowpath, method = c("raster")){

}

#' Extract a vector raster cells of removal and the type of removal for a flowpath
#'
#' This function takes a flowpath as input and extracts out the nitrogen removal
#' and they type of removal.
#'
#' @param flowpath a flowpath to summarize nitrogen removal
#' @param rasters the removal or type rasters, generated by \code{\link{nsink_calc_removal}}
#'
#' @return A vector of all cells along the flowpath with either removal amount
#'         or removal type (depending on input for the rasters argument).
#' @importFrom raster extract
#' @keywords internal
nsink_extract_flowpath_rasters <- function(flowpath, rasters){
  browser()
  fp_extract <- extract(rasters, flowpath, along = TRUE)
  fp_extract[[1]][,1]
}

#' Filters flowpath vector based on a moving window
#'
#' Takes an input flowpath vector of removal or type and returns a filtered
#' vector.
#'
#' @param flowpath_vector a vector of values extracted from either the nitrogren
#'                        removal or type rasters.  These are generated from
#'                        \code{\link{nsink_extract_flowpath_rasters}}.
#' @param filter_window A numeric value indicating the size of the filter
#'                      window. Default value is 3.  See argument description
#'                      for \code{width} from \code{\link{rollapply}}.
#'
#' @return A filtered vector of all cells along the flowpath with either removal
#'         amount or removal type (depending on input for the rasters argument)
#' @importFrom zoo rollapply
#' @keywords internal
nsink_filter_flowpath_rasters <- function(flowpath_vector, filter_window = 3){
  # Why is this a separate function, can just include this line in top level function.
  browser()
  rollmax(flowpath_vector, filter_window)
}

#' Total Reduction
#'
#' Description
#'
#' @param
#'
#' @return
#'
#' @keywords internal
nsink_calc_total_reduction <- function(){
  browser()

}

#' Title
#'
#' Description
#'
#' @param
#'
#' @return
#'
#' @keywords internal
nsink_create_segment_ids <- function(){
  browser()

}

#' Title
#'
#' Description
#'
#' @param
#'
#' @return
#'
#' @keywords internal
nsink_create_summary <- function(){
  browser()

}
